version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: candidate-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PWD
