spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/candidate-db
    username: postgres
    password: PWD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    liquibase: DEBUG